/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Statistic;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-28T21:45:50.925Z")

@Api(value = "statistics", description = "the statistics API")
public interface StatisticsApi {

    @ApiOperation(value = "Get statistics from last 60 seconds", nickname = "getStatistics", notes = "", response = Statistic.class, tags={ "statistics", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = Statistic.class) })
    @RequestMapping(value = "/statistics",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Statistic> getStatistics();

}
